[package]
name = "particles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flo_canvas = "0.3.0"
flo_draw = "0.3.0"
itertools ="0.11.0"
rand ="0.8.5"